# Generated by Django 5.0.7 on 2024-12-29 10:35

import Utils.functions
import Utils.views
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Extras', '0001_initial'),
        ('Food', '0001_initial'),
        ('Instruction', '0001_initial'),
        ('Restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemExtraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extras.extra')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemInstructionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instruction_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruction.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CA', 'Cancelled'), ('PA', 'Paid')], max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('extra_options', models.ManyToManyField(through='Transaction.OrderItemExtraOption', to='Extras.extra')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Food.food')),
                ('food_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='Food.sizemodel')),
                ('instructions', models.ManyToManyField(through='Transaction.OrderItemInstructionOption', to='Instruction.instruction')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AddField(
            model_name='orderiteminstructionoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.ordermodel'),
        ),
        migrations.AddField(
            model_name='orderitemextraoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.ordermodel'),
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('serial', models.IntegerField(default=Utils.views.generate_random_number, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paid_time', models.DateTimeField()),
                ('total_duration', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed'), ('CA', 'Canceled'), ('AC', 'Accepted'), ('DE', 'Declined')], max_length=2)),
                ('latitude', models.TextField(blank=True)),
                ('longitude', models.TextField(blank=True)),
                ('brief_address', models.TextField(blank=True)),
                ('client_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('delivery_code', models.PositiveIntegerField(default=Utils.functions.get_random_num, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction.transactionmodel'),
        ),
    ]
