# Generated by Django 5.0.7 on 2024-12-29 10:35

import Category.models
import Utils.functions
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('icon', models.FileField(upload_to=Category.models.get_category_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
