# Generated by Django 5.0.7 on 2024-12-29 10:35

import Utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('brief_address', models.TextField()),
                ('created_by', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
