# Generated by Django 5.0.7 on 2024-12-29 10:35

import Restaurant.models
import Utils.functions
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drink', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('brief_address', models.TextField()),
                ('image', models.ImageField(upload_to=Restaurant.models.get_restaurant_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('logo', models.ImageField(upload_to=Restaurant.models.get_restaurant_logo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])])),
                ('coverage', models.JSONField(blank=True, default=list)),
                ('drinks', models.ManyToManyField(blank=True, to='Drink.drink')),
                ('owner_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
