# Generated by Django 5.0.7 on 2024-12-29 10:33

import Utils.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.CharField(default=Utils.functions.get_uuid, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('comment_for', models.CharField(max_length=15)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
