# Generated by Django 5.0.7 on 2024-12-29 10:35

import Food.models
import Utils.functions
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to=Food.models.get_food_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('price', models.CharField(max_length=10)),
                ('preparation_time', models.IntegerField(help_text='Write in minutes')),
                ('rating', models.CharField(default='4.3', max_length=5)),
                ('stack', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Category.category')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('price', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
    ]
