# Generated by Django 5.0.7 on 2024-12-29 10:35

import Drink.models
import Utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utils.functions.get_uuid, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to=Drink.models.get_drink_directory)),
                ('price', models.CharField(max_length=10)),
                ('stack', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
