# Generated by Django 5.0.7 on 2024-12-29 10:35

import Utils.functions
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('uuid', models.CharField(default=Utils.functions.get_uuid, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('views', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
    ]
